version: '3'
services:
  client:
    image: edisga/nodejs-client:01
    ports:
       - "3000:3000"
       - "2222:2222"
    depends_on:
       - server
    environment:
       - server_url=http://server:3001

  server:
    image: edisga/nodejs-server:01
    ports:
      - "3001:3001"
